version: 2.1

orbs:
  node: circleci/node@4.3.0
  docker: circleci/docker@1.5.0
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run build
      - store_artifacts:
          path: ./dist

  lint-prettier:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run lint:prettier

  lint-eslint:
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          keys:
            - eslintcache-{{ .Branch }}-{{ checksum ".eslintrc" }}-{{ checksum "yarn.lock" }}
            - eslintcache-{{ .Branch }}-{{ checksum ".eslintrc" }}
            - eslintcache-{{ .Branch }}
            - eslintcache
      - run: yarn run lint:eslint --format junit --output-file ./junit/eslint.xml
      - save_cache:
          key: eslintcache-{{ .Branch }}-{{ checksum ".eslintrc" }}-{{ checksum "yarn.lock" }}
          paths:
            - .eslintcache
      - store_test_results:
          path: ./junit

  ts-check:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run ts-check

workflows:
  version: 2
  develop:
    jobs:
      - lint-eslint
      - lint-prettier
      - docker/hadolint:
          dockerfiles: Dockerfile
      - ts-check
      - build:
          requires:
            - lint-eslint
            - lint-prettier
            - ts-check
      - docker/publish:
          context:
            - ghcr
          requires:
            - docker/hadolint
            - build
          filters:
            branches:
              only: develop
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: ghcr.io
          tag: develop
